import MainLayout from '@/components/layout/MainLayout'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from '@/app/lib/registery'
import { ConfigProvider, Spin } from "./lib/antd";
import theme from './theme/theme'
import { Suspense } from 'react'
import Loading from '@/components/layout/Loading'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigProvider
          theme={theme}
        >
          <StyledComponentsRegistry>
            <MainLayout>
              <Suspense fallback={<Spin />}>
                {children}
              </Suspense>
            </MainLayout>
          </StyledComponentsRegistry>
        </ConfigProvider>
      </body>
    </html>
  )
}

